name: OpenAI Sync

on:
  workflow_dispatch:

jobs:
  run-openai-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenAI sync
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Ready to initiate sync via OpenAI API."
          # You can define here how you'd like the API interaction to behave
